# Clash.Meta
mixed-port: 7890
allow-lan: true
mode: rule
external-controller: :9090
external-ui: clash-dashboard-gh-pages

dns:
  enable: true
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - 1.1.1.1

proxy-groups:

  - name: Auto
    type: fallback
    use:
      - Sub
    url: http://bing.com
    interval: 600

proxy-providers:

#   Sub:
#     type: http
#     url: https://sub.xeton.dev/sub?target=clash&list=true&url=订阅
#     interval: 3600
#     path: ./sub.yaml
#     health-check:
#       enable: true
#       url: http://bing.com
#       interval: 600

  Sub:
    type: http
    url: https://sub.xeton.dev/sub?target=clash&list=true&url=订阅
    interval: 3600
    path: ./sub.yaml
    health-check:
      enable: true
      url: http://bing.com
      interval: 600

rule-providers:
  AdvertisingLite:
    behavior: "classical"
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml"
    interval: 86400
    path: ./AdvertisingLite.yaml

  ProxyLite:
    behavior: "classical"
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.yaml"
    interval: 86400
    path: ./ProxyLite.yaml

  China:
    behavior: "classical"
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml"
    interval: 86400
    path: ./China.yaml


rules:
  - RULE-SET,AdvertisingLite,REJECT
  - RULE-SET,ProxyLite,Auto
  - RULE-SET,China,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Auto
