# Clash.Meta
mixed-port: 7890
allow-lan: true
mode: rule
external-controller: :9090
external-ui: yacd

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8

proxy-groups:

  - name: PROXY
    type: url-test
    use:
      - Sub
    url: http://bing.com

proxy-providers:

#   Sub:
#     type: http
#     url: https://sub.xeton.dev/sub?target=clash&list=true&url=订阅
#     interval: 3600
#     path: ./Sub.yaml
#     health-check:
#       enable: true
#       url: http://bing.com
#       interval: 600

  Sub:
    type: http
    url: https://sub.xeton.dev/sub?target=clash&list=true&url=订阅
    interval: 3600
    path: Sub.yaml
    health-check:
      enable: true
      url: http://bing.com
      interval: 600

rule-providers:
  AdvertisingLite:
    behavior: classical
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml
    interval: 86400
    path: AdvertisingLite.yaml

  ProxyLite:
    behavior: classical
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.yaml
    interval: 86400
    path: ProxyLite.yaml

  SteamCN:
    behavior: classical
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
    interval: 86400
    path: SteamCN.yaml

  China:
    behavior: classical
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml
    interval: 86400
    path: China.yaml


rules:
  # LAN
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  # Rule
  - RULE-SET,AdvertisingLite,REJECT
  - RULE-SET,ProxyLite,PROXY
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,China,DIRECT
  # China
  - GEOIP,CN,DIRECT
  # Final
  - MATCH,PROXY
