# Clash.Meta
proxy-providers:
  sub:
    type: http
    url: https://sub.xeton.dev/sub?target=clash&udp=false&list=true&url=订阅
    path: sub.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.google.com/
      interval: 600

mixed-port: 7890
allow-lan: true
mode: rule
ipv6: false
external-controller: :9090

dns:
  enable: true
  nameserver:
    - 8.8.8.8
    - 114.114.114.114

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Auto
    use:
      - sub
  - name: Auto
    type: url-test
    use:
      - sub

rule-providers:
  AdvertisingLite:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite.yaml
    interval: 86400
    path: AdvertisingLite.yaml

  ProxyLite:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ProxyLite/ProxyLite.yaml
    interval: 86400
    path: ProxyLite.yaml

  SteamCN:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml
    interval: 86400
    path: SteamCN.yaml

  China:
    behavior: classical
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China.yaml
    interval: 86400
    path: China.yaml


rules:
  # Rule
  - RULE-SET,AdvertisingLite,REJECT
  - RULE-SET,ProxyLite,PROXY
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,China,DIRECT
  # China
  - GEOIP,CN,DIRECT
  # Final
  - MATCH,PROXY